services:
  postgres:
    image: postgres
    container_name: produit_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rolisse
      POSTGRES_DB: produits

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '9083:8080'

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produit-container
    restart: always
    ports:
      - '8081:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produits
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rolisse
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres