services:
  postgres:
    image: postgres
    container_name: produit_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rolisse
      POSTGRES_DB: produits

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '9083:8080'